apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demok8s
data:
  database.host: drupal-database-mariadb
  database.port: '3306'
  cache.host: drupal-cache-redis-master
  log.uri: 'http://loki-stack:3100'
