version: "2"

services:
  php:
    environment:
      DRUPAL_DATABASE_HOST: mariadb
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_HASH_SALT: '<some random hash drupal generates a 74 characters long one>'
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: mypassword
      LOGGING_URI: 'http://loki:3100'
    volumes:
      - ./:/var/www/html

  nginx:
    volumes:
      - ./:/var/www/html

  redis:
    environment:
      REDIS_PASSWORD: mypassword

  traefik:
    ports:
      - '8000:80'
      - '8080:8080' # Dashboard
