version: "2"

services:
  php:
    environment:
      DRUPAL_DATABASE_HOST: mariadb
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_HASH_SALT: '<some random hash drupal generates a 74 characters long one>'
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: mypassword
      LOGGING_URI: 'http://loki:3100'
    volumes:
      - ./:/var/www/html

  nginx:
    volumes:
      - ./:/var/www/html

  redis:
    environment:
      REDIS_PASSWORD: mypassword

#  ## <-- LOGGING --> ##
# @todo: Maybe try https://medium.com/the-devs-tech/logging-with-fluent-bit-influxdb-282c9bc35245
  loki:
    image: grafana/loki:1.5.0
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - promtail_data:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml

  grafana:
    image: grafana/grafana:7.1.1
    labels:
      - "traefik.http.services.${PROJECT_NAME}_grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.${PROJECT_NAME}_grafana.rule=Host(`grafana.${PROJECT_BASE_URL}`)"

volumes:
  promtail_data: {}
