apiVersion: v1
kind: Secret
metadata:
  name: demok8s-drupal
type: Opaque
data:
  drupal-hash-salt: "bkVldEx0YzIxazZOX3pIbkt0QmVVWXNjT3VGRHJzN28wMGp6T0ZpYnQwUmhRbWdxcFFrRzlteEpHOG9PeURtVzdaWjBWNTVXMmc="
