kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demok8s-app-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
## Start app.
kind: Pod
apiVersion: v1
metadata:
  name: demok8s-app
  labels:
    app: demok8s-app
spec:
  securityContext:
    fsGroup: 1000
  containers:
    # Our PHP-FPM application
    - image: brainsum/k8sdemo:7.4-dev-4.15.8
      imagePullPolicy: "IfNotPresent"
      name: drupal
      env:
        - name: PHP_FPM_USER
          value: wodby
        - name: PHP_FPM_GROUP
          value: wodby
        - name: PHP_POST_MAX_SIZE
          value: "500M"
        - name: PHP_UPLOAD_MAX_FILESIZE
          value: "500M"
        - name: DRUPAL_DATABASE_HOST
          value: drupal-database-mariadb
        - name: DRUPAL_DATABASE_PORT
          value: "3306"
        - name: DRUPAL_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mariadb-username
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mariadb-password
        - name: DRUPAL_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mariadb-db-name
        - name: DRUPAL_HASH_SALT
          valueFrom:
            secretKeyRef:
              name: demok8s-drupal
              key: drupal-hash-salt
      ports:
        - name: fastcgi
          containerPort: 9000
          protocol: TCP
      volumeMounts:
        - name: drupal-data
          mountPath: /var/www/html/private_files
          subPath: private_files
        - name: drupal-data
          mountPath: /var/www/html/web/sites/default/files
          subPath: files

    # Our nginx container, which uses the configuration declared above,
    # along with the files shared with the PHP-FPM app.
    - image: brainsum/k8sdemo-nginx:1.17-5.8.15
      imagePullPolicy: "IfNotPresent"
      name: nginx
      env:
        - name: NGINX_STATIC_OPEN_FILE_CACHE
          value: "off"
        - name: NGINX_ERROR_LOG_LEVEL
          value: debug
        - name: NGINX_BACKEND_HOST
          value: "localhost:9000"
        - name: NGINX_SERVER_ROOT
          value: /var/www/html/web
        - name: NGINX_CLIENT_MAX_BODY_SIZE
          value: "500m"
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
      volumeMounts:
        - name: drupal-data
          mountPath: /var/www/html/private_files
          subPath: private_files
        - name: drupal-data
          mountPath: /var/www/html/web/sites/default/files
          subPath: files
  volumes:
    - name: drupal-data
      persistentVolumeClaim:
        claimName: demok8s-app-pvc
