kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-database-backups-pvc
  namespace: demok8s
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
